name: Moodle Plugin CI
on: push
jobs:
  test:
    #    env:
    #      IGNORE_PATHS: js/jquery.js,tests/
    strategy:
      fail-fast: false
      matrix:
        database: ['pgsql', 'mariadb']
        moodle-version: ['MOODLE_38_STABLE', 'MOODLE_39_STABLE', 'MOODLE_310_STABLE']
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    runs-on: ${{ matrix.operating-system }}
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Install node
        uses: actions/setup-node@v1
        with:
          # TODO: Check if we can support .nvmrc
          node-version: '14.15.0'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pgsql, mysqli
          tools: phpunit
          coverage: none
          ini-values: sendmail_path = "/usr/sbin/sendmail -t -i "

      - name: Deploy moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          # Add dirs to $PATH
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          # PHPUnit depends on en_AU.UTF-8 locale
          sudo locale-gen en_AU.UTF-8
      - name: Install Moodle
        run: moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-version }}

      - name: phplint
        run: moodle-plugin-ci phplint

      - name: phpcpd
        run: moodle-plugin-ci phpcpd

      - name: phpmd
        run: moodle-plugin-ci phpmd

      - name: codechecker
        run: moodle-plugin-ci codechecker

      - name: validate
        run: moodle-plugin-ci validate

      - name: savepoints
        run: moodle-plugin-ci savepoints

        # We have to skip mustache because it yields a false failure
        # - name: mustache
        # - run: moodle-plugin-ci mustache

        # Silencing some tests while working on migration.
        # - name: grunt
        # - run: moodle-plugin-ci grunt

      - name: phpunit
        run: moodle-plugin-ci phpunit

      - name: behat
        run: moodle-plugin-ci behat
